version: '3.1'
services:
  server:
    build:
      context: .
      dockerfile: docker-config/tomcat/Dockerfile
    ports:
      - "8080:8080"
    links:
      - database:database
    depends_on:
      - database

  database:
    image: mysql
    command: mysqld --innodb-buffer-pool-size=20M
    volumes:
      - ./docker-config/mysql:/var/lib/mysql:rw
      - ./src/main/resources/SQL:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "3306:3306"
  angular:
    build:
      context: docker-config/nginx
    volumes:
     - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
     - "4200:80"
    environment:
     - NGINX_HOST=test.dev
     - NGINX_PORT=80