# DROP USER 'SpringAppUser'@'localhost';
CREATE USER 'SpringAppUser'@'localhost' IDENTIFIED BY 'SpringAppUser';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'SpringAppUser'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;